name = "ip"
account_id = "30a0df93b283fb485840d7fddbca58ba"
compatibility_date = "2025-11-26"

main = "src/index.ts"

workers_dev = false
preview_urls = false

[[routes]]
pattern = "ip.willow.sh"
custom_domain = true

[observability]
enabled = true
